name: Run dev and load test deployment

on:
  push:
    branches:
      - main

jobs:
  startHere:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0    

  detectChanges:
    needs: startHere
    # JOB to run change detection
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      aepModelChange: 'true'
      apiChange: 'false'
    steps:
      - run: echo detectChanges

  dependsOnaepModelChange:
    name: Publish PREVIEW AEP image
    needs: [startHere, detectChanges]
    if: ${{ needs.detectChanges.outputs.aepModelChange == 'true'}}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo dependsOnaepModelChange ${{ needs.detectChanges.outputs.aepModelChange }}
          exit 1

  dependsOnapiChange:
    needs: [startHere, detectChanges]
    if: ${{ needs.detectChanges.outputs.apiChange  == 'true'}}
    runs-on: ubuntu-latest
    steps:
      - run: echo dependsOnapiChange

  dependsOnDependant:
    name: Smoketests
    needs: [startHere, dependsOnaepModelChange, dependsOnapiChange]
    if: ${{ always() }} && ${{ needs.dependsOnaepModelChange.result == 'success' }} && ( ${{ needs.detectChanges.outputs.aepModelChange  == 'true'}} || ${{ needs.detectChanges.outputs.apiChange  == 'true'}})
    runs-on: ubuntu-latest
    steps:
      - run: echo dependsOnDependant ${{  needs.dependsOnaepModelChange.result }}

  finalJob:
    name: Publish release AEP image
    needs: [dependsOnDependant, dependsOnaepModelChange]
    if: ${{ always() }} && ${{ !failure() }}
    runs-on: ubuntu-latest
    steps:
      - run: echo finalJob