name: Run dev and load test deployment

on:
  push:
    branches:
      - main

jobs:
  startHere:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0    

  detectChanges:
    needs: startHere
    # JOB to run change detection
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      changeA: true
      changeB: false


  dependsOnChangeA:
    needs: [startHere, detectChanges]
    if: needs.detectChanges.outputs.changeA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
            
  dependsOnChangeB:
    needs: [startHere, detectChanges]
    if: needs.detectChanges.outputs.changeB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

  dependsOnDependant:
    needs: [startHere, dependsOnChangeA, dependsOnChangeB]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0