name: Run dev and load test deployment

on:
  push:
    branches:
      - main

jobs:
  startHere:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0    

  detectChanges:
    needs: startHere
    # JOB to run change detection
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      dataapi: ${{ steps.filter.outputs.dataapi }}
      orchestrator: ${{ steps.filter.outputs.orchestrator }}
      models: ${{ steps.filter.outputs.models }}
      infrastructure: ${{ steps.filter.outputs.infrastructure }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0      
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        base: 'main'
        filters: |
          dataapi:
            - 'src/api/**'
          orchestrator:
            - 'orchestrator/**'
          models:
            - 'model/aep/**'
          infrastructure:
            - 'infrastructure/**'

  dependsOnChange:
    needs: [startHere, detectChanges]
    if: needs.detectChanges.outputs.dataapi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
            
  dependsOnDependant:
    needs: [startHere, dependsOnChange]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0